### ISSUE TITLE
build not working out of the box:

### ISSUE THREAD

**Issue by demarco88** [gematik/app-VZD-Client#1]
D:\app-VZD-Client>gradle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'VZD-Client'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.jeysal:gradle-graphviz-plugin:1.4.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/jeysal/gradle-graphviz-plugin/1.4.1/gradle-graphviz-plugin-1.4.1.pom
       - https://jcenter.bintray.com/com/github/jeysal/gradle-graphviz-plugin/1.4.1/gradle-graphviz-plugin-1.4.1.pom
     Required by:
         project : > de.gematik:documentation-plugin:1.1.2

**Comment by patrickbussmann** [comment]
Haha, funny @demarco88.
Yesterday I forked the repository and tried the same: Building the client.
And yes, I had the same issue with building so I decided to create a GitHub workflow for it and fixing the issue.

Now only 26 are not working - but ZIP file and TAR files are generated.

[VZD-Client-1.1.0.zip](https://github.com/gematik/app-VZD-Client/files/5312370/VZD-Client-1.1.0.zip)

**Comment by demarco88** [comment]
@patrickbussmann someone other than me is interessted in the VZD client?!?! That's great, I test your fork and the build is working now!! thx!
@Gematik-Entwicklung: It's working with gradle 5.6.2; 6.6.1 is given an error->perhaps unsing a wrapper

**Comment by Gematik-Entwicklung** [comment]
Thanks for Feedback. 
Currently we build with gradle 5.6.2. and would update to gradle 6 in the near future.
See documentation for Build-Setup: https://github.com/gematik/app-VZD-Client/#build-setup

**Comment by Gematik-Entwicklung** [comment]
Sorry for the inconveniences. 

The [changes](https://github.com/gematik/app-VZD-Client/pull/2) suggested by Patrick will be included in the next release, so that you can build the project out of the box.

Thanks to @patrickbussmann
