### ISSUE TITLE
gematik PU is not supported?

### ISSUE THREAD

**Issue by patrickbussmann** [gematik/app-VZD-Client#3]
I have a simple question to @Gematik-Entwicklung (because I get no reply to my mail to the userhelpdesk).

In the API documentation there is a API for Reference Environment (RU) and Productive Environment (PU).
I got credentials for both of them.

When I use the Reference Environment (RU), its working.
POST https://auth-ref.[...]/auth/realms/RSDirectoryAdministration/protocol/openid-connect/token
```
{
    "access_token": "----",
    "expires_in": 18000,
    "refresh_expires_in": 1800,
    "refresh_token": "----",
    "token_type": "bearer",
    "not-before-policy": 0,
    "session_state": "----",
    "scope": "VZD:DirectoryAdministration"
}
```

But when I try the same with Productive Environment (PU), its not working.
POST https://auth.[...]/auth/realms/RSDirectoryAdministration/protocol/openid-connect/token
```
Error: write EPROTO 1644261544:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40
1644261544:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:588:
```

Do you know why?

Thanks in Advance!

When someone knows a mail address where I get a reply it would be nice, too.

**Comment by Gematik-Entwicklung** [comment]
Hello @patrickbussmann,

Is this problem still persistent? There was recently a VZD update. Can you confirm the existence of the error?

If so, are you using the client and you get this error?

Best regards

**Comment by patrickbussmann** [comment]
Yes @Gematik-Entwicklung the issue still exists.
The productive environment (PU) is not working.

My client sent a mail to the bertelsmann userhelpdesk now and hopefully it's fixed soon.

Does nobody works with productive environment yet? Or is the documentation out of date?

**Comment by patrickbussmann** [comment]
The productive environment (PU) is working now.
Thanks
